server:
  port: 9999
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka
zuul:
  host:
    socket-timeout-millis: 40000
    connection-request-timeout-millis: 60000
    connect-timeout-millis: 60000
